# Generated by Django 3.2.6 on 2021-08-06 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabelis', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=120)),
                ('surname', models.CharField(default='', max_length=200)),
                ('kategorija', models.CharField(default='K01', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Darbuotojai',
                'ordering': ['tabelis'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('country', models.CharField(default='Lietuva', max_length=150)),
                ('started', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('finished', models.DateField(blank=True, default='', null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Objektai',
                'ordering': ['finished', 'started'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(blank=True, default='', null=True)),
                ('tarrif', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.project')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priedas_geras_darbas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('apmokymas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kelione_Lietuva', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kelione_uzsienis', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('koordinatoriaus_priedas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('daugiau_nei_12_savaiciu', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('klaida_algalapyje', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('naujas_darbuotojas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kita', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.projectdate')),
            ],
            options={
                'verbose_name_plural': 'Bonusai',
                'ordering': ['-project'],
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
