# Generated by Django 3.2.6 on 2021-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
