# Generated by Django 3.2.6 on 2021-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_bonus_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdate',
            name='year_month',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
