# Generated by Django 3.2.6 on 2021-08-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_projectdate_year_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdate',
            options={'ordering': ['year_month']},
        ),
        migrations.CreateModel(
            name='EmployeeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('laukas1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('laukas2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
            options={
                'ordering': ['employee'],
            },
        ),
    ]
