# Generated by Django 3.2.6 on 2021-08-06 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('company_code', models.IntegerField()),
                ('representative', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scaffolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastolio_numeris', models.CharField(max_length=200, unique=True)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('lenght', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='', max_length=250)),
                ('order_date', models.DateField(default=datetime.datetime(2021, 8, 6, 8, 3, 10, 790645, tzinfo=utc))),
                ('assembled_date', models.DateField(null=True)),
                ('dismanatled_date', models.DateField(null=True)),
                ('stable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('base_leveled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('number_of_braces', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('platform_guardrails_height', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('gaps_35mm', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('stable_structure', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('proper_sideboards', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('metal_perforated_grating_completely_covers', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('safe_entrance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('stiff_and_secured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('tag_filled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('marked_noticed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N//A', 'N//A')], default='Yes', max_length=50)),
                ('active', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('deliver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.deliver')),
                ('scaffoldig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.scaffolding')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
    ]
