# Generated by Django 3.2.6 on 2021-08-06 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 6, 9, 14, 54, 728516, tzinfo=utc)),
        ),
    ]
